server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#配置mybatis-plus
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations:
#    classpath*:/mapper/*.xml
#  global-config:
#    banner: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  typeAliasesPackage: com.roc.SuperMaster.domain
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    auto-mapping-unknown-column-behavior: warning
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID #19位数字
      field-strategy: NOT_EMPTY
      capital-mode: true
      logic-delete-field: del
      logic-delete-value: 1
      logic-not-delete-value: 0