server:
  port: 9000    #端口号

spring:
  datasource:   #数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver   #数据库连接驱动
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8    #数据库URL
    username: root    #账户
    password: 123456    #密码

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  typeAliasesPackage: com.roc.SuperMaster.domain
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    auto-mapping-unknown-column-behavior: warning
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #Mybatis-plus开启日志
  global-config:
    banner: false   #mybatis-plus：banner配置
    db-config:
      id-type: ASSIGN_ID #19位数字
      field-strategy: NOT_EMPTY
      capital-mode: true
      logic-delete-field: del
      logic-delete-value: 1
      logic-not-delete-value: 0



#logging:
#  level:   ##打印sql
#    com.roc.SuperMaster.mapper: debug   # mapper/dao层的路径